### ISSUE TITLE
No module named 'commonImports'

### ISSUE THREAD

**Issue by catketchup** [IftachSadeh/ANNZ#5]
Hi,

I have trouble importing " scripts.helperFuncs ". I run " from scripts.helperFuncs import * ". There is an Error: " ModuleNotFoundError: No module named 'commonImports' " . Do you have any idea what's going on? I appreciate it.

Hongbo

**Comment by IftachSadeh** [comment]
Try adding the corresponding directory to `PYTHONPATH `, as mentioned in `README.md`.

**Comment by Anjitha-JM** [comment]
Hi, 
I have a trouble in compilation. When I compile this: python scripts/annz_singleReg_quick.py --make, it shows error.
(21:00 INFO)  - Setting ROOTSYS = "/snap/root-framework/158/usr/local/"
(21:00 INFO)  - Setting LD_LIBRARY_PATH = "/snap/root-framework/158/usr/local//lib/"
(21:00 INFO)  - Resetting directory(/home/anjitha/ANNZ-master/lib,False)
(21:00 INFO)  - Moving to /home/anjitha/ANNZ-master/lib and compiling ANNZ... 
c++ -O2 -Wall -fPIC -pthread -std=c++17 -m64 -I/snap/root-framework/158/usr/local/include -g -I../ -I./ -I../src/ -I../include/ -std=c++0x -include commonInclude.hpp -c -o myANNZ.o ../src/myANNZ.cpp
In file included from /snap/root-framework/158/usr/local/include/TString.h:29:0,
                 from /snap/root-framework/158/usr/local/include/TNamed.h:26,
                 from /snap/root-framework/158/usr/local/include/TDirectory.h:24,
                 from /snap/root-framework/158/usr/local/include/TROOT.h:28,
                 from ../include/commonInclude.hpp:44,
                 from <command-line>:0:
/snap/root-framework/158/usr/local/include/ROOT/RStringView.hxx:19:23: fatal error: string_view: No such file or directory
compilation terminated.
/home/anjitha/ANNZ-master/Makefile:159: recipe for target 'myANNZ.o' failed
make: *** [myANNZ.o] Error 1
(21:00 CRITICAL) compilation failed
(21:00 CRITICAL) Will terminate !!!!
